# docker compose to help testing custom integration

services:
  hass:
    image: ghcr.io/home-assistant/home-assistant:latest
    volumes:
      - hass_config:/config
      - ./config/configuration.yaml:/config/configuration.yaml:ro
      - ./custom_components:/config/custom_components:ro
    ports:
       - "8123:8123/tcp"

volumes:
  hass_config:
